### PR TITLE
[WIP] Use dependency injection in FlushQueueCommand

### PR DESCRIPTION
**Pull request by brotkrueml**

### CODE REVIEW

**Comment by brotkrueml** [comment]
The patch moves the dependencies into the constructor. In TYPO3 v10 the dependency to CrawlerController will be injected (with patch #597), in TYPO3 v9 the old instantiation is used. This has also the benefit that the command can now tested easily, as a mock can be given.

@tomasnorre What do you think about it?

**Comment by brotkrueml** [comment]
@tomasnorre What is the best way to get the functional tests working on local machine? I started ddev and followed the steps in travis.yml but only get errors.

**Comment by tomasnorre** [comment]
> @tomasnorre What is the best way to get the functional tests working on local machine? I started ddev and followed the steps in travis.yml but only get errors.

The https://github.com/AOEpeople/crawler/blob/master/.Docker/docker-compose.yml can be used to boot a local mysql with `docker-compose` and the run the `composer test:functional` should do the trick for you.

**Comment by tomasnorre** [comment]
> The patch moves the dependencies into the constructor. In TYPO3 v10 the dependency to CrawlerController will be injected (with patch #597), in TYPO3 v9 the old instantiation is used. This has also the benefit that the command can now tested easily, as a mock can be given.
> 
> @tomasnorre What do you think about it?

I like that approach it cleaner, than what I did.

**Comment by brotkrueml** [comment]
> The https://github.com/AOEpeople/crawler/blob/master/.Docker/docker-compose.yml can be used to boot a local mysql with `docker-compose` and the run the `composer test:functional` should do the trick for you.

Okay, I tried that: `docker-compose up` - mysqld is running from container. Then the `composer test:functional` returns error: `Call to undefined function mysqli_init()`. As I understand the PHP from my local machine is used. It's a PHP 7.2 with installed mysql extension. Do you have an idea what causes this error?

**Comment by tomasnorre** [comment]
Hmm. A missing php-mysql extension would be my first guess too. It is you local PHP which is used.

https://github.com/AOEpeople/crawler/blob/master/CONTRIBUTING.md#running-tests-without-local-development-environment  has an example on how to run them with the devbox setup.

**Comment by brotkrueml** [comment]
> Hmm. A missing php-mysql extension would be my first guess too. It is you local PHP which is used.
> 
> https://github.com/AOEpeople/crawler/blob/master/CONTRIBUTING.md#running-tests-without-local-development-environment has an example on how to run them with the devbox setup.

Thought about it, RTFD ;-)

Okay, ddev is up and running, logging into ddev and running unit tests are fine. Running functional tests: Connection refused. Now, changed the command to `TYPO3_PATH_WEB=$PWD/.Build/Web typo3DatabaseName=db typo3DatabaseHost=db typo3DatabaseUsername=db typo3DatabasePassword=db .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml Tests/Functional` for ddev database, now `Access denied for user 'db'@'%' to database 'db_ft8aa95de'`

Does it run for you out of the box?

**Comment by tomasnorre** [comment]
I honestly haven't tested. Would need to check

**Comment by tomasnorre** [comment]
Hi @brotkrueml 
If you do following: 

```shell
$ ddev ssh 
$ mysql -uroot -proot
mysql> GRANT ALL PRIVILEGES ON `db\_%` .  * TO 'db'@'%';
mysql> FLUSH PRIVILEGES;
```
Then the composer test:functional that you posted above will work. 

I'll make sure to update the ddev configuration for the devbox, so that it works out of the box.

**Comment by brotkrueml** [comment]
Thanks. Some tests fail again with "Connection refused".

But I think I know why the functional FlushQuereCommandTest is failing failing: In 9.5 no DI is available, so the command name is the parameter for the constructor (it's a string). In v10, the name is given via DI. But: Perhaps the DI is not available (yet?) in the testing framework, so also the v10 tests are failing.

**Comment by tomasnorre** [comment]
I haven't used the DI yet, so I cannot say, but perhaps @IchHabRecht can say something about that for the Nimut Testing Framework.

**Comment by IchHabRecht** [comment]
I didn't read the whole thread but nimut testing framework doesn't support dependency injection. It is recommended to set up dependencies on your own to ensure to how what they are doing.

**Comment by tomasnorre** [comment]
Still relevant...

**Comment by tomasnorre** [comment]
Any news one this @brotkrueml?

**Comment by brotkrueml** [comment]
Will close for now, perhaps will come to it later.

**Pull request closed without merging**
