### PR TITLE
[TASK] Add before step to rector

### PR DESCRIPTION
**Pull request by tomasnorre**

### CODE REVIEW

**Comment by tomasnorre** [comment]
Not needed @TomasVotruba will fix it in next PR.

**Comment by TomasVotruba** [comment]
I can see that now, pretty hidden

**Comment by tomasnorre** [comment]
Yeah, I also just saw it by coincidence, it due to bad structure of the travis-ci.yml that one would oversee that part.

**Comment by TomasVotruba** [comment]
We'll fix that :)

**Pull request closed without merging**
