### PR TITLE
[TASK] reactivate realurl functionality

### PR DESCRIPTION
**Pull request by samowitsch**
We have maybe a really rare case in our project but in our setup we need the crawler realurl functionality. I took  the changes suggested from issue #87 from motordigital/crawler@04ab00c and fixed the realurl functionality. This issue/pullrequest is related to #87, #88 and #201 (and #208 ?).

TYPO3 7.6.23
realurl 2.3.0
crawler 5.2.0-dev

### CODE REVIEW

**Comment by tomasnorre** [comment]
Thanks for your suggestion, we need to take a look into this before we can merge. 

Can you try to describe you problem a little more, and why the changes are needed?

**Comment by samowitsch** [comment]
@tomasnorre Hi. TYPO3 stays in background and acts in our environment as an template/content generator. Our frontend driven by another framework recognizes if cli crawler is running. In that case a template file would be written (to folder(s)/templatefile) depending to speaking url.
Looking at the crawler code we found that realurl is supported but was not activated.
With this pull request we can eliminate one redirect and could optimize crawling speed in our case.

**Comment by samowitsch** [comment]
@tomasnorre another argument to keep the realurl feature is generating static files for example with nc_staticfilecache.

**Comment by tomasnorre** [comment]
Thanks, I know ;)

**Comment by samowitsch** [comment]
Any decisions here? Regards

**Comment by tomasnorre** [comment]
@samowitsch No we haven't looked into it yet, sorry.

**Comment by chriwo** [comment]
I have test the fix and however, this does not work correctly or I have misconfigured something. The first generated URL looks correct, but every next URL includes the URL before.

_Example:_
1. URL: http://www.domain.de/segment/title.html
2. URL: http://www.domain.de/http://www.domain.de/segment/title.html/segment/title2.html
3. URL: http://www.domain.de/http://www.domain.de/http://www.domain.de/segment/title.html/segment/title2.html/segment/title3.html

The URL's above are created with `$urlObj->encodeUrl($params);` and saved into the RealUrl tables. So every manipulation after this lines are ineffective.

_Test-Environment:_
- TYPO3 7.6.23
- realurl: 2.3.0
- crawler 5.2.0-dev (with this patch)

**Comment by tomasnorre** [comment]
@samowitsch  We will try to get this prioritized asap, but cannot promise when.

**Comment by samowitsch** [comment]
@chriwo thx, for your test. I think i forgot to enable the existing realurl checkbox in tca for the config record. I have added a commit to this pull request. Maybe you have enabled the use of realurl in mysql directly?
Neverless i could not reproduce your described behavior of concatenating urls.
table tx_realurl_urldata speaking_url stays clean.
We us a very simple config with just a Base url and activated realurl.

Screenshot of crawler queue:
crawler-queue-with-speaking-urls

**Comment by chriwo** [comment]
@samowitsch Thanks for your feedback. For normal pages it looks really good, but I configured the crawler for tx_news. The result of the URLs is the same as I had previously described. Here is a screenshot of how I configured the crawler for tx_news.

crawler_txnews_config

**Comment by samowitsch** [comment]
Oh, i see... in ext:realurl (2.3.0) UrlEncoder.php:128 => method encodeUrl() => $this->encodedUrl appends itself each time.

**Comment by samowitsch** [comment]
@chriwo Hi. I added as first line
`	    $this->encodedUrl = '';
`
in method encodeUrl() of ext:realurl. 
This fixes the issue for me. I found no other way to reset this property of the UrlEncode class. I opened for this a pull request here https://github.com/dmitryd/typo3-realurl/pull/560

**Comment by chriwo** [comment]
@samowitsch Yeaa, that looks really good!!! Many thanks, great job!

**Comment by samowitsch** [comment]
Hi. See @dimitryd comment here https://github.com/dmitryd/typo3-realurl/pull/560#issuecomment-346992502.

**Comment by samowitsch** [comment]
Hm, whats your opinion, move the realurl block in function urlListFromUrlArray into the foreach on $vv['URLs']? Then needed changes are only on ext:crawler.

**Comment by tomasnorre** [comment]
@samowitsch  I've been home sick in bet the last week.. Will look into this again when i'm back on my feed.

**Comment by samowitsch** [comment]
?

**Comment by tomasnorre** [comment]
@samowitsch  Sorry.. Didn't find the time yet.

**Comment by dklimpel** [comment]
[CrawlerController.diff.txt](https://github.com/AOEpeople/crawler/files/1716557/CrawlerController.diff.txt)

The patch for the current master.

**Comment by tomasnorre** [comment]
We cannot merge this as long as it's drops Support for RealURL 1.x. 

Besides from that there are merge conflicts, so I will not review till this is fixed. 

Pull Requests are more than welcome, but we need to keep support for RealUrl 1.x too.

**Comment by tomasnorre** [comment]
As we will not support RealURL 2.0 I'll reject this PR.

**Pull request closed without merging**
