### PR TITLE
[TASK] Add and optimize some behavior tests

### PR DESCRIPTION
**Pull request by tomasnorre**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I'll try to run this PR locally and see what goes wrong with Rector

**Comment by TomasVotruba** [comment]
I might have an idea... [`PropertyProperty` is actually subnode of `Property`](https://github.com/rectorphp/rector/blob/master/docs/nodes_overview.md#phpparsernodestmtproperty). 

So maybe the docblock is detected on wrong node. Will investigate

**Comment by TomasVotruba** [comment]
Of course that's it :) 

Would you like to send PR, since you've invested a lot into issue report?

It's pretty simple, just update this class: https://github.com/rectorphp/rector/blob/master/src/Exclusion/Check/ExcludeByDocBlockExclusionCheck.php#L15

```diff
+use PhpParser\Node\Const_;
+use PhpParser\Node\Stmt\PropertyProperty;

// ...

public function isNodeSkippedByRector(PhpRectorInterface $phpRector, Node $node): bool
    {
+       if ($node instanceof PropertyProperty || $node instanceof Const_) {
+           $node = $node->getAttribute(AttributeKey::PARENT_NODE);
+       }

        $comment = $node->getDocComment();
        if ($comment !== null && $this->checkCommentForIgnore($phpRector, $comment)) {
            return true;
        }
```

**Comment by tomasnorre** [comment]
I'll check and send PR.

**Comment by tomasnorre** [comment]
It's working but the tests `composer complete-check` isn't green. 

```
$ vendor/bin/phpstan analyse --ansi --error-format symplify

 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 src/Exclusion/Check/ExcludeByDocBlockExclusionCheck.php:24
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 - '#Cannot call method getDocComment\(\) on PhpParser\\Node\|null#'
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 src/Exclusion/Check/ExcludeByDocBlockExclusionCheck.php:30
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 - '#Cannot call method getAttribute\(\) on PhpParser\\Node\|null#'
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

The problem as I see it is that the 
```
 if ($node instanceof PropertyProperty || $node instanceof Const_) {
            $node = $node->getAttribute(AttributeKey::PARENT_NODE);
        }
```

resolves in a different node class or null where the `->getComment()` and `->getAttribute()` isn't available.

**Comment by TomasVotruba** [comment]
What do you suggest?

**Comment by tomasnorre** [comment]
I'll have to consider that to have the code as clean as possible. :)

**Comment by tomasnorre** [comment]
```php
 if ($node instanceof PropertyProperty || $node instanceof Const_) {
            $node = $node->getAttribute(AttributeKey::PARENT_NODE);
            if ($node === null) {
                return false;
            }
        }
```

This would be my suggestion. By will not commit before I hear your comments.

**Comment by TomasVotruba** [comment]
Exactly my thoughts.

**Pull request merged**
