### PR TITLE
[FEATURE] Deprecates EventDispatcher + Adds Signal Slots (#252)

### PR DESCRIPTION
**Pull request by tomasnorre**

### CODE REVIEW

**Comment by kaystrobach** [comment]
Looks good from reading, wouldn’t it make sense to wrap the old signal with a function to make it possible to have an entry in the deprecation log?

**Comment by tomasnorre** [comment]
Thanks @kaystrobach 

That makes perfectly good sense. Will do that.

**Comment by bmack** [comment]
👍

**Comment by tomasnorre** [comment]
@kaystrobach and @bmack 
What do you think about adding deprecations to the class
https://github.com/AOEpeople/crawler/blob/issue/252/Classes/Event/EventDispatcher.php

Then I don't need to wrapper it in functions like Kay suggested? It's sort of already wrapped.

**Comment by kaystrobach** [comment]
Valid point

**Comment by tomasnorre** [comment]
Is it enough to deprecate the constructor? or should I deprecate every single function, isn't that many so no a problem, just wanna know what you suggests.

**Comment by kaystrobach** [comment]
I think the constructor is enough if the medsage is clear, which means, the whole object should not be used.

**Pull request merged**
